sonar.projectKey=LugSys_nodejs-sonarcloud
sonar.organization=lugsys
sonar.sourceEncoding=UTF-8
sonar.language=.
sonar.sources=.
sonar.exclusions=node_modules/**,**/*.test.js,**/*.spec.js
sonar.tests=.
sonar.test.inclusions=**/*.test.js,**/*.spec.js
sonar.javascript.coveragePlugin=lcov
sonar.javascript.lcov.reportPaths=coverage/lcov.info
